version: '3.8'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  api:
    container_name: urticket-backend-dev
    image: urticket-backend-dev:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
    links:
      - postgres
    networks:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - docker.env
    networks:
      - postgres
    restart: always

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge
