version: '3.8'
services:
  api:
    image: quankhs/urticket-backend-dev:latest
    ports:
      - '5000:5000'
    command: ['node', 'dist/main.js']
    depends_on:
      - postgres
    networks:
      - urticket
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initialize-postgres/:/docker-entrypoint-initdb.d/
    env_file:
      - docker.env
    networks:
      - urticket
    restart: always

networks:
  urticket:
    driver: bridge
