version: '3.8'

services:
  api:
    container_name: urticket-backend-dev
    image: quankhs/urticket-backend-dev:latest
    command: npm run start:prod
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
    links:
      - postgres
    networks:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initialize-postgres/:/docker-entrypoint-initdb.d/
    env_file:
      - docker.env
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge
