version: '3.8'
services:
  api:
    image: quankhs/urticket-backend-dev:latest
    ports:
      - '5000:5000'
    command: ['node', 'dist/main.js']
    depends_on: 
      - postgres
    networks:
      - urticket
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initialize-postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: quankhs
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: urticket
    networks:
      - urticket
    restart: always

networks:
  urticket:
    driver: bridge
