name: Build and Deploy

on:
  push:
    branches: [master]
env:
  IMAGE_NAME: urticket-backend-dev
  PROJECT_PATH: project

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Decode base64 env secrets
        shell: bash -c "echo ${{ secrets.ENV_SECRET }} | base64 --decode > /github_token.txt"

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  
            
            
