name: Build and Deploy

on:
  push:
    branches: [master]
env:
  IMAGE_NAME: urticket-backend-dev
  PROJECT_PATH: /project

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: 'Deploy Server'
    needs: [build-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: SSH and deploy in Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            git clone git@github.com:QuanKhs/urTicket-backend.git
            
