name: Build and Deploy

on:
  push:
    branches: [master]
env:
  IMAGE_NAME: urticket-backend-dev
  PROJECT_PATH: project

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Decode base64 env secrets
        run: |
          echo "UE9SVD01MDAwDQoNClBPU1RHUkVTX0hPU1Q9cG9zdGdyZXMNClBPU1RHUkVTX1BPUlQ9NTQzMg0K
UE9TVEdSRVNfVVNFUj1xdWFua2hzDQpQT1NUR1JFU19QQVNTV09SRD0xMjM0NTYNClBPU1RHUkVT
X0RCPXVydGlja2V0DQoNCkpXVF9BQ0NFU1NfVE9LRU5fU0VDUkVUPXF1YW5raHNfYWNjZXNzX3Rv
a2VuX3NlY3JldF9rZXkNCkpXVF9BQ0NFU1NfVE9LRU5fRVhQSVJBVElPTl9USU1FPTg2NDAwDQpK
V1RfUkVGUkVTSF9UT0tFTl9TRUNSRVQ9cXVhbmtoc19yZWZyZXNoX3Rva2VuX3NlY3JldF9rZXkN
CkpXVF9SRUZSRVNIX1RPS0VOX0VYUElSQVRJT05fVElNRT00MzIwMDANCkJFQVJFUj1CZWFyZXIN
Cg0KRU1BSUxfU0VSVklDRT1nbWFpbA0KRU1BSUxfVVNFUj1ib29raW5nbW92aWUuYXBwbGljYXRp
b25AZ21haWwuY29tDQpFTUFJTF9QQVNTV09SRD11cnRpY2tldGphY2tzb24NCg0KSldUX1ZFUklG
SUNBVElPTl9UT0tFTl9TRUNSRVQ9N0FuRWQ1ZXBYbWRhSmZVcm9ra1ENCkpXVF9WRVJJRklDQVRJ
T05fVE9LRU5fRVhQSVJBVElPTl9USU1FPTg2NDAwDQpFTUFJTF9DT05GSVJNQVRJT05fVVJMPWh0
dHA6Ly9sb2NhbGhvc3Q6MzAwMC9jb25maXJtLWVtYWlsDQoNCkpXVF9GT1JHT1RfUEFTU1dPUkRf
VE9LRU5fU0VDUkVUPTdBbkVkNWVwWG1kYUpmVXJva2tRDQpKV1RfRk9SR09UX1BBU1NXT1JEX0VY
UElSQVRJT05fVElNRT04NjQwMA0KRU1BSUxfRk9SR09UX1BBU1NXT1JEX1VSTD1odHRwOi8vbG9j
YWxob3N0OjMwMDAvZm9yZ290LXBhc3N3b3JkDQoNCkFXU19SRUdJT049dXMtZWFzdC0xDQpBV1Nf
QUNDRVNTX0tFWV9JRD1BS0lBWU9BTUdQVEFOWTNLTzVIMw0KQVdTX1NFQ1JFVF9BQ0NFU1NfS0VZ
PWtzL09DYzhycFJNYitJRE5XODlsMXpQV2hOTC8xVEJ2KzQ2L1NPTisNCkFXU19QVUJMSUNfQlVD
S0VUX05BTUU9dXItdGlja2V0LXB1YmxpYy1idWNrZXQNCg0KU1RSSVBFX1NFQ1JFVF9LRVk9c2tf
dGVzdF81MUpWbzVlS1VmVUZCcFNwTnZTdnNlRUhNWDdnVlRHeVlTV012YWpmMnBDMVQ2MThoQnYw
OVd6U2FVS2JPcVBvcER3Tk9Yc2hQc2c0V09ueHV0Y0RJY2ZhSjAwaU5XNUJzc1cNClNUUklQRV9D
VVJSRU5DWT11c2QNCkZST05URU5EX1VSTD1odHRwOi8vbG9jYWxob3N0OjMwMDA=" | base64 -d > .env
          cat .env
          ls -a
        env:
          ENV_SECRET: '${{ secrets.ENV_SECRET }}'

      # - name: Login Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      # - name: Verify
      #   run: echo ${{ steps.docker_build.outputs.digest }}
