name: Deployment to Server

on:
  workflow_dispatch:

env:
  IMAGE_NAME: quankhs/urticket-backend-dev:latest
  PROJECT_PATH: project/urticket-backend

jobs: 
  deployment: 
    runs-on: ubuntu-latest

    steps:
      - name: Deploy digitalocean
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            docker-compose down
            docker pull ${{ env.IMAGE_NAME }}
            docker-compose up -d
            docker image prune -f
